# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('department', models.CharField(default='', max_length=250, null=True)),
                ('level', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
